
{ pkgs, lib, ... }:

{


  # Containers
  virtualisation.oci-containers.containers."homepage-web-interface" = {
    image = "ghcr.io/gethomepage/homepage:latest";
    environment = {
      "HOMEPAGE_ALLOWED_HOSTS" = "homepage.tailb1bb3f.ts.net";
    };
    volumes = [
      "/mnt/storage:/mnt/storage:ro"
      "/var/lib/homepage/config:/app/config:rw"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "127.0.0.1:8000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web-interface"
      "--network=homepage_default"
    ];
  };
  systemd.services."docker-homepage-web-interface" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-homepage_default.service"
    ];
    requires = [
      "docker-network-homepage_default.service"
    ];
    partOf = [
      "docker-compose-homepage-root.target"
    ];
    wantedBy = [
      "docker-compose-homepage-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-homepage_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homepage_default";
    };
    script = ''
      docker network inspect homepage_default || docker network create homepage_default
    '';
    partOf = [ "docker-compose-homepage-root.target" ];
    wantedBy = [ "docker-compose-homepage-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homepage-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
