name: homepage
services:
  web-interface:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 127.0.0.1:8000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/storage:/mnt/storage:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.tailb1bb3f.ts.net
