# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  options.tandoor = {
    enable = lib.mkEnableOption "Enable tandoor";
  };

  config = lib.mkIf config.tandoor.enable {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."tandoor-db_recipes" = {
      image = "postgres:16-alpine";
      environmentFiles = [
        "/run/agenix/tandoor"
      ];
      volumes = [
        "/mnt/storage/tandoor/postgresql:/var/lib/postgresql/data:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=db_recipes"
        "--network=tandoor_default"
      ];
    };
    systemd.services."docker-tandoor-db_recipes" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-tandoor_default.service"
      ];
      requires = [
        "docker-network-tandoor_default.service"
      ];
      partOf = [
        "docker-compose-tandoor-root.target"
      ];
      wantedBy = [
        "docker-compose-tandoor-root.target"
      ];
    };
    virtualisation.oci-containers.containers."tandoor-web_recipes" = {
      image = "vabene1111/recipes";
      environmentFiles = [
        "/run/agenix/tandoor"
      ];
      volumes = [
        "/mnt/storage/tandoor/mediafiles:/opt/recipes/mediafiles:rw"
        "tandoor_staticfiles:/opt/recipes/staticfiles:rw"
      ];
      ports = [
        "127.0.0.1:8003:80/tcp"
      ];
      dependsOn = [
        "tandoor-db_recipes"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=web_recipes"
        "--network=tandoor_default"
      ];
    };
    systemd.services."docker-tandoor-web_recipes" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-tandoor_default.service"
        "docker-volume-tandoor_staticfiles.service"
      ];
      requires = [
        "docker-network-tandoor_default.service"
        "docker-volume-tandoor_staticfiles.service"
      ];
      partOf = [
        "docker-compose-tandoor-root.target"
      ];
      wantedBy = [
        "docker-compose-tandoor-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-tandoor_default" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f tandoor_default";
      };
      script = ''
        docker network inspect tandoor_default || docker network create tandoor_default
      '';
      partOf = [ "docker-compose-tandoor-root.target" ];
      wantedBy = [ "docker-compose-tandoor-root.target" ];
    };

    # Volumes
    systemd.services."docker-volume-tandoor_staticfiles" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        docker volume inspect tandoor_staticfiles || docker volume create tandoor_staticfiles
      '';
      partOf = [ "docker-compose-tandoor-root.target" ];
      wantedBy = [ "docker-compose-tandoor-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-tandoor-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
