# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  options.immich = {
    enable = lib.mkEnableOption "Enable immich";
  };

  config = lib.mkIf config.immich.enable {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."immich-database" = {
      image = "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23";
      environmentFiles = [
        "/run/agenix/immich"
      ];
      volumes = [
        "/mnt/storage/immich/postgres:/var/lib/postgresql/data:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=database"
        "--network=immich_default"
        "--shm-size=134217728"
      ];
    };
    systemd.services."docker-immich-database" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-immich_default.service"
      ];
      requires = [
        "docker-network-immich_default.service"
      ];
      partOf = [
        "docker-compose-immich-root.target"
      ];
      wantedBy = [
        "docker-compose-immich-root.target"
      ];
    };
    virtualisation.oci-containers.containers."immich-machine-learning" = {
      image = "ghcr.io/immich-app/immich-machine-learning:v3";
      environmentFiles = [
        "/run/agenix/immich"
      ];
      volumes = [
        "immich_model-cache:/cache:rw"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=machine-learning"
        "--network=immich_default"
      ];
    };
    systemd.services."docker-immich-machine-learning" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-immich_default.service"
        "docker-volume-immich_model-cache.service"
      ];
      requires = [
        "docker-network-immich_default.service"
        "docker-volume-immich_model-cache.service"
      ];
      partOf = [
        "docker-compose-immich-root.target"
      ];
      wantedBy = [
        "docker-compose-immich-root.target"
      ];
    };
    virtualisation.oci-containers.containers."immich-redis" = {
      image = "docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411";
      environmentFiles = [
        "/run/agenix/immich"
      ];
      log-driver = "journald";
      extraOptions = [
        "--health-cmd=redis-cli ping || exit 1"
        "--network-alias=redis"
        "--network=immich_default"
      ];
    };
    systemd.services."docker-immich-redis" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-immich_default.service"
      ];
      requires = [
        "docker-network-immich_default.service"
      ];
      partOf = [
        "docker-compose-immich-root.target"
      ];
      wantedBy = [
        "docker-compose-immich-root.target"
      ];
    };
    virtualisation.oci-containers.containers."immich-server" = {
      image = "ghcr.io/immich-app/immich-server:v3";
      environmentFiles = [
        "/run/agenix/immich"
      ];
      volumes = [
        "/etc/localtime:/etc/localtime:ro"
        "/mnt/storage/immich/library:/data:rw"
      ];
      ports = [
        "127.0.0.1:8001:2283/tcp"
      ];
      dependsOn = [
        "immich-database"
        "immich-redis"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=server"
        "--network=immich_default"
      ];
    };
    systemd.services."docker-immich-server" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-immich_default.service"
      ];
      requires = [
        "docker-network-immich_default.service"
      ];
      partOf = [
        "docker-compose-immich-root.target"
      ];
      wantedBy = [
        "docker-compose-immich-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-immich_default" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f immich_default";
      };
      script = ''
        docker network inspect immich_default || docker network create immich_default
      '';
      partOf = [ "docker-compose-immich-root.target" ];
      wantedBy = [ "docker-compose-immich-root.target" ];
    };

    # Volumes
    systemd.services."docker-volume-immich_model-cache" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        docker volume inspect immich_model-cache || docker volume create immich_model-cache
      '';
      partOf = [ "docker-compose-immich-root.target" ];
      wantedBy = [ "docker-compose-immich-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-immich-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
