# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  options.vikunja = {
    enable = lib.mkEnableOption "Enable vikunja";
  };

  config = lib.mkIf config.vikunja.enable {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."vikunja-server" = {
      image = "vikunja/vikunja:2.5.0";
      environment = {
        "VIKUNJA_DATABASE_PATH" = "/db/vikunja.db";
        "VIKUNJA_SERVICE_PUBLICURL" = "https://vikunja.tailb1bb3f.ts.net/";
        "VIKUNJA_SERVICE_SECRET" = "d45985fc54c7a14a8132c2bf22b91dfb7455cd594fe62152841bca1009c5b68e";
      };
      volumes = [
        "/mnt/storage/vikunja/db:/db:rw"
        "/mnt/storage/vikunja/files:/app/vikunja/files:rw"
      ];
      ports = [
        "127.0.0.1:8002:3456/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=server"
        "--network=vikunja_default"
      ];
    };
    systemd.services."docker-vikunja-server" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-vikunja_default.service"
      ];
      requires = [
        "docker-network-vikunja_default.service"
      ];
      partOf = [
        "docker-compose-vikunja-root.target"
      ];
      wantedBy = [
        "docker-compose-vikunja-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-vikunja_default" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f vikunja_default";
      };
      script = ''
        docker network inspect vikunja_default || docker network create vikunja_default
      '';
      partOf = [ "docker-compose-vikunja-root.target" ];
      wantedBy = [ "docker-compose-vikunja-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-vikunja-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
