# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."filebrowser-web-interface" = {
    image = "gtstef/filebrowser:stable";
    volumes = [
      "/mnt/storage/old_archive:/storage/old_archive:rw"
      "/var/lib/filebrowser/data:/home/filebrowser/data:rw"
    ];
    ports = [
      "127.0.0.1:8000:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web-interface"
      "--network=filebrowser_default"
    ];
  };
  systemd.services."docker-filebrowser-web-interface" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-filebrowser_default.service"
    ];
    requires = [
      "docker-network-filebrowser_default.service"
    ];
    partOf = [
      "docker-compose-filebrowser-root.target"
    ];
    wantedBy = [
      "docker-compose-filebrowser-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-filebrowser_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f filebrowser_default";
    };
    script = ''
      docker network inspect filebrowser_default || docker network create filebrowser_default
    '';
    partOf = [ "docker-compose-filebrowser-root.target" ];
    wantedBy = [ "docker-compose-filebrowser-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-filebrowser-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
