name: filebrowser
services:
  web-interface:
    image: gtstef/filebrowser:stable
    volumes:
      - ./data:/home/filebrowser/data
      - /mnt/storage/old_archive:/storage/old_archive
    ports:
      - 127.0.0.1:8000:80
    restart: unless-stopped
